spring:
  datasource:
    url: jdbc:postgresql://ep-divine-shape-a1iecro0-pooler.ap-southeast-1.aws.neon.tech/expensedb?sslmode=require&channel_binding=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: "npg_D1REQAI6wmKp"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
